import type { Types } from 'mongoose'
import { Schema, model, type HydratedDocument } from 'mongoose'

import { applyAuditPlugin, auditFieldsDefinition } from './plugins/audit-fields.plugin'
import type { AuditFields } from './shared/audit-fields.type'

export const CERTIFICATE_STATUSES = ['ACTIVE', 'REVOKED'] as const
export type CertificateStatus = (typeof CERTIFICATE_STATUSES)[number]

/**
 * `certificateNumber` is the public lookup key for certificate verification
 * — it MUST be non-sequential and non-guessable (generated by the service
 * layer as a ULID/UUID, never the Mongo `_id` or an incrementing number) to
 * resist enumeration on the public, unauthenticated verification endpoint
 * (SECURITY.md §5, §7). Revocation is a status transition, not a deletion —
 * the record must remain for verification/audit history.
 */
export interface ICertificate extends AuditFields {
  studentId: Types.ObjectId
  courseId: Types.ObjectId
  certificateNumber: string
  issuedAt: Date
  status: CertificateStatus
  pdfUrl: string | null
  revokedReason: string | null
  revokedAt: Date | null
}

export type CertificateDocument = HydratedDocument<ICertificate>

const certificateSchema = new Schema<ICertificate>({
  studentId: { type: Schema.Types.ObjectId, ref: 'Student', required: true },
  courseId: { type: Schema.Types.ObjectId, ref: 'Course', required: true },
  certificateNumber: { type: String, required: true, trim: true, minlength: 16 },
  issuedAt: { type: Date, default: Date.now },
  status: { type: String, enum: CERTIFICATE_STATUSES, default: 'ACTIVE' },
  pdfUrl: { type: String, default: null },
  revokedReason: { type: String, default: null, trim: true, maxlength: 500 },
  revokedAt: { type: Date, default: null },
  ...auditFieldsDefinition,
})

applyAuditPlugin(certificateSchema)

certificateSchema.index({ certificateNumber: 1 }, { unique: true })
certificateSchema.index({ studentId: 1, courseId: 1 })

export const CertificateModel = model<ICertificate>(
  'Certificate',
  certificateSchema,
  'certificates',
)
